### ISSUE TITLE
AttributeError: 'Settings' object has no attribute 'TEMPLATE_LOADERS'

### ISSUE THREAD

**Issue by tehfink** [centralniak/cmsplugin_gallery#51]
Fresh install of Django 1.11.15, cms 3.5.2, filer 1.3.2. After running `makemigrations`:
```python
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/tehfink/…/virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/tehfink/…/virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/tehfink/…/virtualenv/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/tehfink/…/virtualenv/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/tehfink/…/virtualenv/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/tehfink/…/virtualenv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tehfink/…/virtualenv/lib/python3.6/site-packages/cmsplugin_gallery/models.py", line 22, in <module>
    localdata.TEMPLATE_CHOICES = utils.autodiscover_templates()
  File "/Users/tehfink/…/virtualenv/lib/python3.6/site-packages/cmsplugin_gallery/utils.py", line 41, in autodiscover_templates
    if 'django.template.loaders.app_directories.Loader' in settings.TEMPLATE_LOADERS:
  File "/Users/tehfink/…/virtualenv/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'TEMPLATE_LOADERS'
```

According to the [Django docs](https://docs.djangoproject.com/en/1.11/ref/templates/upgrading/), `TEMPLATE_LOADERS` may not necessarily be defined, and it seems that the template settings in 1.11 are namespaced in a dict. The following seems to function as a workaround:
```python
TEMPLATE_LOADERS = TEMPLATES[0]['OPTIONS']['loaders']
TEMPLATE_DIRS = TEMPLATES[0]['DIRS']
```

**Comment by vinitkumar** [comment]
We can have something like this:

```python
        if is_django_18_or_later:
            TEMPLATE_CONTEXT_PROCESSORS = settings['TEMPLATES'][0]['OPTIONS']['context_processors']
            TEMPLATE_LOADERS = settings['TEMPLATES'][0]['OPTIONS']['loaders']
        else:
            TEMPLATE_CONTEXT_PROCESSORS = settings['TEMPLATE_CONTEXT_PROCESSORS']
            TEMPLATE_LOADERS = settings['TEMPLATE_LOADERS']

```

I would suggest that you just define the TEMPLATE setting as per the docs and it should just for you. What the plugin is doing is here works for both old and new version of django, I myself use django1.11.15 and djangoCMS 3.5.2.

**Comment by mosesibe** [comment]
Hey, am all set, have pip installed it.
but how do i get the images stored on the plugin to display on the website(frontend).

**Comment by vinitkumar** [comment]
@mosesibe Once you installed the plugin, you will need to add the plugin to the `INSTALLED_APPS` to the settings.py file of your app. 

After this, you will need to run `python manage.py migrate` to do the migrations.  Once all of this is done, you will get the plugin in the front-end editing of the website. Over there, you could get add images in the plugin. If you have confusions about the front-end editing works, please watch this video. https://vimeo.com/187947268

I hope this helps :+1:

**Comment by mosesibe** [comment]
Thank you for replying. 
I've done all you mentioned. i have used the plugin to add images into it. now i thing my templates can't display it thats the problem please any ideas on wht to do next?

**Comment by vinitkumar** [comment]
@mosesibe Make sure your templates are same as this: https://github.com/centralniak/cmsplugin_gallery/blob/master/cmsplugin_gallery/templates/cmsplugin_gallery/gallery.html

Also, check the console on your browser, looks like you have some issues with your media file and path. Make sure you fix those if that's why you are not seeing the files in correct place.

**Comment by mosesibe** [comment]
Ok Thank  you. its showing now. 
Problem no2. (am a pain in the ass at this point) am sorry
the overlay is not working it just displaying all the big images right under the thumbnails.
console error: TypeError: jQuery(...).overlay is not a function

**Comment by vinitkumar** [comment]
@mosesibe Look like a JS issues. Make sure you have the proper JS libraries in the html, else, it will give this kind of errors. In this case, looks like you missing this library http://jquerytools.github.io/documentation/overlay/

**Comment by mosesibe** [comment]
Thanks very much. the Overlay cdn wasn't working but i figured another way and change template file accordingly. works great. thanks A lot buddy. Have a nice  day

**Comment by lukyncze** [comment]
Hello, I have a same error as @tehfink, but I don´t know how to fix it. Any ideas?

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "D:\Final-project\env\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "D:\Final-project\env\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "D:\Final-project\env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\Final-project\env\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "D:\Final-project\env\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\lukas\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Final-project\env\lib\site-packages\cmsplugin_gallery\models.py", line 22, in <module>
    localdata.TEMPLATE_CHOICES = utils.autodiscover_templates()
  File "D:\Final-project\env\lib\site-packages\cmsplugin_gallery\utils.py", line 41, in autodiscover_templates
    if 'django.template.loaders.app_directories.Loader' in settings.TEMPLATE_LOADERS:
  File "D:\Final-project\env\lib\site-packages\django\conf\__init__.py", line 77, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'TEMPLATE_LOADERS'

**Comment by vinitkumar** [comment]
@mosesibe Please check the thread above and do as it is recommended and then let me know if that works for you not.
